export const CLIENTS = [
  {
    name: "Avgi",
    id: "01",
    category: "Rebranding & Identity",
    image: "/hero/Avgi.jpeg",
    color: "#a68a69",
    accent: "#aecae8",
    location: "Global",
    comment:
      "A complete visual overhaul and strategic repositioning for a high-fashion house.",
    services: ["Logo Design", "Brand Strategy", "Packaging"],
    ceo: {
      name: "Elena Vardi",
      title: "Founder & Creative Director",
      email: "elena@avgi.com",
      bio: "Former luxury fashion executive with 15+ years in Paris and Milan.",
    },
  },
  {
    name: "Brazaville",
    id: "02",
    category: "E-Commerce Architecture",
    image: "/hero/brazaville.jpeg",
    color: "#004741",
    accent: "#00584C",
    location: "Congo / International",
    comment:
      "Engineered a high-conversion digital flagship for premium coffee grounds.",
    services: ["UI/UX", "Shopify Plus", "Inventory Sync"],
    ceo: {
      name: "Claude Mbiya",
      title: "CEO & Head Roaster",
      email: "claude@brazaville.co",
      bio: "Third‑generation coffee grower turned tech entrepreneur.",
    },
  },
  {
    name: "Broken Arrow",
    id: "03",
    category: "Product Branding",
    image: "/hero/broken-arrow.jpeg",
    color: "#e15d0a",
    accent: "#a3a3a3",
    location: "USA",
    comment:
      "Aggressive visual identity for a disruptive consumer product line.",
    services: ["Identity", "Product Design", "Logo"],
    ceo: {
      name: "Jesse Hart",
      title: "Founder & Chief Product Officer",
      email: "jesse@brokenarrow.com",
      bio: "Ex‑military turned product designer with a passion for rugged aesthetics.",
    },
  },
  {
    name: "Fixtoce",
    id: "04",
    category: "Real Estate Systems",
    image: "/hero/Fixtoce.jpeg",
    color: "#2c3639",
    accent: "#a27b5b",
    location: "Dubai, UAE",
    comment:
      "A high-performance property portal for Dubai's luxury real estate sector.",
    services: ["Web App", "DX Integration", "3D Tours"],
    ceo: {
      name: "Karim Al‐Farsi",
      title: "Managing Director",
      email: "karim@fixtoce.ae",
      bio: "Former real estate investor with a vision for digital transformation.",
    },
  },
  {
    name: "KicksStore",
    id: "05",
    category: "Mobile Engineering",
    image: "/hero/kicksstore.webp",
    color: "#e11d48",
    accent: "#000000",
    location: "USA",
    comment:
      "Scalable mobile commerce app for the high-end sneaker secondary market.",
    services: ["React Native", "API Arch", "Mobile UX"],
    ceo: {
      name: "Marcus Chen",
      title: "Co‑Founder & CTO",
      email: "marcus@kicksstore.com",
      bio: "Sneaker collector and full‑stack engineer who built the platform from scratch.",
    },
  },
  {
    name: "Maapilim",
    id: "06",
    category: "E-Commerce",
    image: "/hero/maapilim.jpeg",
    color: "#B3A695",
    accent: "#CA886E",
    location: "Tel Aviv",
    comment:
      "A minimalist, sensory-driven web experience for premium body care.",
    services: ["Web Design", "Conversion Opt", "headless"],
    ceo: {
      name: "Tamar Cohen",
      title: "CEO & Head of Product",
      email: "tamar@maapilim.com",
      bio: "Biochemist turned entrepreneur, focusing on clean beauty.",
    },
  },
  {
    name: "Mark Dowson",
    id: "07",
    category: "Consultancy Branding",
    image: "/hero/mark-dowson.jpeg",
    color: "#925E51",
    accent: "#2F404A",
    location: "London, UK",
    comment: "Precision branding for a top-tier UK corporate consulting firm.",
    services: ["Corporate ID", "Stationery", "Web Presence"],
    ceo: {
      name: "Mark Dowson",
      title: "Founder & Principal Consultant",
      email: "mark@markdowson.com",
      bio: "Former McKinsey partner with a passion for brand strategy.",
    },
  },
  {
    name: "Nectar",
    id: "08",
    category: "Digital Storefront",
    image: "/hero/nectar.jpeg",
    color: "#E4AE10",
    accent: "#4b2c20",
    location: "Europe",
    comment:
      "Synthesizing the artisanal feel of honey & coffee into a digital shop.",
    services: ["Web Build", "Brand Assets", "Storytelling"],
    ceo: {
      name: "Sophie Laurent",
      title: "Co‑Founder & Creative Director",
      email: "sophie@nectar.eu",
      bio: "Sommelier turned digital storyteller, focusing on sensory experiences.",
    },
  },
  {
    name: "FitNess Urban",
    id: "09",
    category: "Mobile App & Brand",
    image: "/hero/fitness-urban.webp",
    color: "#E4AE10",
    accent: "#000000",
    location: "Lagos / NYC",
    comment:
      "A fitness ecosystem designed for the modern urban high-performer.",
    services: ["App Dev", "Brand System", "UX Research"],
    ceo: {
      name: "Adebayo Ogunlesi",
      title: "CEO & Lead Trainer",
      email: "bayoo@fitnessurban.com",
      bio: "Ex‑athlete and tech enthusiast bridging fitness and digital tools.",
    },
  },
  {
    name: "TShirtUrban",
    id: "10",
    category: "Web & Branding",
    image: "/hero/tshirturban.jpeg",
    color: "#3C5D4A",
    accent: "#EAE9E5",
    location: "Berlin",
    comment: "Streetwear aesthetics met with robust e-commerce architecture.",
    services: ["Full Stack", "Brand Identity", "Motion"],
    ceo: {
      name: "Lena Schmidt",
      title: "Founder & Head of Design",
      email: "lena@tshirturban.com",
      bio: "Streetwear designer with a background in urban art and e‑commerce.",
    },
  },
];
